import { bed, bed1, bed2, bed3, bed4, bed5, bed6, bed7, bed8, bed9, bed10, chair, kitchen, kitchen1, livingroom, livingroom1, livingroom2, livingroom3, livingroom4, livingroom5, livingroom6, makeup, house } from "../assets";
import { faLocationDot, faPlus, faMinus } from "@fortawesome/free-solid-svg-icons"

export const hero = [
  {
    id: "bed",
    img: bed,
    superhost: true,
    type: "Entire house",
    title: "Your Insta-Worthy Home Base",
    beds: 3,
    rating: 4.8,
    location: "Vaasa, Finland",
  },
  {
    id: "kitchen",
    img: kitchen,
    superhost: true,
    type: "Entire apartment",
    title: "Nature's Haven: Your Urban Oasis",
    beds: 2,
    rating: 4.9,
    location: "Vaasa, Finland",
  },
  {
    id: "bed4",
    img: bed4,
    superhost: false,
    type: "Private room",
    title: "Find Serenity in Your Private Retreat",
    beds: null,
    rating: 4.6,
    location: "Vaasa, Finland",
  },
  {
    id: "house",
    img: house,
    superhost: false,
    type: "Entire apartment",
    title: "Apartment Vibes On Fleek",
    beds: 3,
    rating: 4.5,
    location: "Vaasa, Finland",
  },
  {
    id: "bed1",
    img: bed1,
    superhost: false,
    type: "Private room",
    title: "The Ultimate Chill Spot",
    beds: null,
    rating: 4.6,
    location: "Vaasa, Finland",
  },
  {
    id: "livingroom",
    img: livingroom,
    superhost: true,
    type: "Entire house",
    title: "Chill Vibes Homey Feels",
    beds: 4,
    rating: 4.9,
    location: "Vaasa, Finland",
  },
  {
    id: "livingroom6",
    img: livingroom6,
    superhost: false,
    type: "Entire house",
    title: "Trendy Living: Unleash Your Cool",
    beds: 5,
    rating: 4.7,
    location: "Helsinki, Finland",
  },
  {
    id: "bed3",
    img: bed3,
    superhost : false,
    type: "Private room",
    title: "Unlock Your Private Oasis & Stay Weird",
    beds: null,
    rating: 4.7,
    location: "Helsinki, Finland",
  },
  {
    id: "livingroom1",
    img: livingroom1,
    superhost: true,
    type: "Entire apartment",
    title: "Level Up Your Stay",
    beds: 2,
    rating: 4.6,
    location: "Helsinki, Finland",
  },
  {
    id: "chair",
    img: chair,
    superhost: true,
    type: "Entire house",
    title: "Unleash Your Vibes in a Whole House",
    beds: 4,
    rating: 4.9,
    location: "Turku, Finland",
  },
  {
    id: "bed9",
    img: bed9,
    superhost: false,
    type: "Entire house",
    title: "Secure the Bag, Entire House Swag",
    beds: 3,
    rating: 4.5,
    location: "Helsinki, Finland",
  },
  {
    id: "bed8",
    img: bed8,
    superhost: false,
    type: "Entire apartment",
    title: "Step into Luxury, Apartment Spree",
    beds: 5,
    rating: 4.7,
    location: "Turku, Finland",
  },
  {
    id: "makeup",
    img: makeup,
    superhost: false,
    type: "Entire apartment",
    title: "Luxe Living",
    beds: 2,
    rating: 4.6,
    location: "Oulu, Finland",
  },
  {
    id: "bed5",
    img: bed5,
    superhost: false,
    type: "Entire apartment",
    title: "Vintage Soul in our Trendy Apartment",
    beds: 5,
    rating: 4.6,
    location: "Oulu, Finland",
  },
  {
    id: "kitchen1",
    img: kitchen1,
    superhost: true,
    type: "Entire apartment",
    title: "Dive into Modern Living",
    beds: 3,
    rating: 4.8,
    location: "Oulu, Finland",
  },
  {
    id: "bed6",
    img: bed6,
    superhost: false,
    type: "Private room",
    title: "Ballin' in a Private Pad",
    beds: null,
    rating: 4.4,
    location: "Oulu, Finland",
  },
  {
    id: "bed2",
    img: bed2,
    superhost: false,
    type: "Entire apartment",
    title: "Apartment Goals: Where Style Meets Comfort",
    beds: 2,
    rating: 4.5,
    location: "Oulu, Finland",
  },
  {
    id: "bed7",
    img: bed7,
    superhost: true,
    type: "Entire house",
    title: "Cool & Chic Home",
    beds: 5,
    rating: 4.8,
    location: "Oulu, Finland",
  },
  {
    id: "livingroom4",
    img: livingroom4,
    superhost: true,
    type: "Entire apartment",
    title: "Vibrant Apartment Life",
    beds: 4,
    rating: 4.9,
    location: "Oulu, Finland",
  },
  {
    id: "bed10",
    img: bed10,
    superhost: false,
    type: "Private room",
    title: "Cozy Retreat for Me Time",
    beds: null,
    rating: 4.6,
    location: "Turku, Finland",
  },
  {
    id: "livingroom5",
    img: livingroom5,
    superhost: true,
    type: "Entire house",
    title: "Own the Space, Whole House Grace",
    beds: 5,
    rating: 4.9,
    location: "Turku, Finland",
  },
  {
    id: "livingroom2",
    img: livingroom2,
    superhost: false,
    type: "Private room",
    title: "Serene Sanctuary Just for You",
    beds: null,
    rating: 4.7,
    location: "Turku, Finland",
  },
  {
    id: "livingroom3",
    img: livingroom3,
    superhost: false,
    type: "Entire apartment",
    title: "Modern Living Redefined",
    beds: 3,
    rating: 4.6,
    location: "Turku, Finland",
  }

]

export const location = [
  {
    id: "Helsinki",
    icon: faLocationDot,
    name: "Helsinki, Finland"
  },
  {
    id: "Turku",
    icon: faLocationDot,
    name: "Turku, Finland"
  },
  {
    id: "Oulu",
    icon: faLocationDot,
    name: "Oulu, Finland"
  },
  {
    id: "Vaasa",
    icon: faLocationDot,
    name: "Vaasa, Finland"
  }
]

export const guests = [
  {
    id: "Adults",
    iconplus: faPlus,
    iconminus: faMinus,
    name: "Adults",
    condition: "Ages 13 or above"
  },
  {
    id: "Children",
    iconplus: faPlus,
    iconminus: faMinus,
    name: "Children",
    condition: "Ages 2-12"
  }
]
